#!/bin/sh

if [ "$#" -ne 4 ]; then
    echo "Forma de uso: $0 <num_facilidades> <num_niveles> <tam_cola> <num_workers>"
    exit
fi
echo "Lanzando el sislog"

# Falta el & para que se ejecute en segundo plano
java -cp clases:clases/rabbitmq-client.jar -Djava.security.policy=policy sislog.Sislog $1 $2 $3 $4 
